---
## bare metal provisioning

#- name: get passwords
#  hosts: all
#  remote_user: root
#  gather_facts: false
#  roles:
#    - ../roles/passwords

- name: baremetal provisioning
  hosts: all
  gather_facts: false
  roles:
    - HPEOneview_Ansible/roles/provisioning/tasks/addserver.yaml
  environment:
    PYTHONPATH: "$PYTHONPATH:/usr/share/ansible"
    ONEVIEWSDK_IP: 10.2.137.41 #"{{ oneview_auth.ip }}"
    ONEVIEWSDK_USERNAME: administrator #"{{ oneview_auth.username }}"
    ONEVIEWSDK_PASSWORD: changeme! #"{{ oneview_pw }}"
    ONEVIEWSDK_API_VERSION: 2200 #"{{ oneview_auth.api_version }}"